import UIKit

struct StringConstants {
    static let k: String = ""
    static let kLblSustainability: String = "Sustainability"
    static let kLblSearch: String = "Search"
    static let kMsgDonTHaveAnA: String = "Don’t have an account?"
    static let kMsgBuyLessChoos: String = "buy less,\nchoose less,\nmake it last."
    static let kLblTrending: String = "Trending"
    static let kMsgClothesAcces: String = "Clothes &\nAccessories"
    static let kMsgThriving4Gmail: String = "Thriving4@gmail.com"
    static let kLblBiowears: String = "BioWears"
    static let kMsgOffTheShoulde: String = "Off-the-shoulder Top\nRp279,900"
    static let kLblNearMe: String = "Near me "
    static let kLblLogIn: String = "Log In"
    static let kLblRating35: String = "Rating (3-5)"
    static let kHttpFail: String = "HTTP request failed"
    static let kMsgSeeingHowThe: String =
        "Seeing how the fast fashion industry is producing lots of waste, we aim to provide a solution to give consumers the ability to try on clothes virtually at home and buy thrifted clothes at the palm of their hands. "
    static let kLblFindStores: String = "Find stores "
    static let kLblAccessories: String = "Accessories"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kLblStores: String = "Stores"
    static let kLblSignUp: String = "Sign up"
    static let kLblNew: String = "New"
    static let kLblSale: String = "Sale"
    static let kLblOuters: String = "Outers"
    static let kMsgLogIntoYourA: String = "Log into your\naccount"
    static let kLblBottoms: String = "Bottoms"
    static let kLblOnePiece: String = "One-piece"
    static let kLblTops: String = "Tops"
    static let kInvalidUrl: String = "Invalid URL"
    static let kLblRememberMe: String = "Remember me"
    static let kMsgJosephineLinen: String = "Josephine Linen Top\nRp 2,430,100\n2 colors"
}
